CC = /usr/bin/gcc
CXX = /usr/bin/g++
LD = /usr/bin/g++
FC=/usr/bin/g77

ARCH=i686-m64
CXXFLAGS = -m64 -Wall -I/Users/pblunsom/packages/include 
CFLAGS = -m64 -Wall -I/Users/pblunsom/packages/include 
FFLAGS = -m64 -Wall
LDFLAGS = -L/Users/pblunsom/packages/lib -lboost_program_options -lm -lz

FFLAGS += -g -O3 -funroll-loops #-pg
CFLAGS += -g -O3 -funroll-loops #-pg
CXXFLAGS += -g -O3 -funroll-loops #-pg
LDFLAGS += -g -O3 -funroll-loops #-pg
